---
title: "jissutools"
format: gfm
---

<!-- README.md is generated from README.qmd. Please edit that file -->

## Overview

調査実習で使える関数を作ってみました。やる気があれば多項ロジットなどもつくります。

## Installation

以下のコードを実行してください

```{r}
#| eval: false

if(!require(remotes)) install.packages("remotes")
remotes::install_github("Kentaro-Kamada/jisshutools")

library(jisshutools)

```


## Usage

- 2変数のクロス表

```{r}
#| eval: false

# Create a sample data
data <-
  data.frame(
    x = c(rep('A', 50), rep('B', 50)),
    y = c(rep(1:5, 20))
  )

# Create a cross table
result <- data |> jisshu_cross(x, y)

# Save the cross table as an excel file
result$save('hoge.xlsx')

```


- 線形回帰・2項ロジスティック回帰

```{r}
#| eval: false

# Create a sample data
data <- tibble::tibble(
  x1 = rnorm(100, mean = 0, sd = 1),
  y = 0.2 + 0.3*x1 + 0.5*x2 + rnorm(100, mean = 0, sd = 0.1),
  y_bin = rbinom(100, 1, plogis(y))
)

# Create a regression table
# Linear regression
model_lm <- lm(y ~ x1 + x2, data = data)
result_lm <- jisshu_reg(model_lm)

# Logistic regression
model_glm <- glm(y_bin ~ x1 + x2, data = data, family = binomial(link = 'logit'))
result_glm <- jisshu_reg(model_glm)

# Save the regression table as an excel file
result_lm$save('hoge_lm.xlsx')
result_glm$save('hoge_glm.xlsx')

```

